import { useState } from 'react'
import { Alert, Button, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { apiRequest } from '../../api/generated/client'
import { useActiveCompany } from '../companies/useActiveCompany'

interface EtlRun { id: string; sourceFile: string; sourceTable: string; stage: string; status: string; sourceRows: number; importedRows: number; quarantinedRows: number; error?: string | null }
const tables = ['ShortList','Languages','Staff','Address','Partner','Company','BuildingEntrance','Unit','Contract','PartnerAccount','BankAccount','InvoiceBatch','Invoice','SupplierInvoice','BankStatement','JournalEntry','LedgerEntry','Notice','InterestStatement','SentEmail','Documents']
export function EtlRunsPage() {
  const { activeCompany } = useActiveCompany(); const client = useQueryClient(); const [file, setFile] = useState<File>(); const [sourceTable, setSourceTable] = useState('ShortList')
  const key = ['etl-runs', activeCompany.id]
  const runs = useQuery({ queryKey: key, queryFn: () => apiRequest<EtlRun[]>(`/api/v1/companies/${activeCompany.id}/etl-runs`) })
  const upload = useMutation({ mutationFn: () => { if (!file) throw new Error('Izaberite CSV fajl.'); const form = new FormData(); form.append('file', file); form.append('sourceTable', sourceTable); form.append('sourceSystem', 'Access'); form.append('encoding', 'windows-1250'); form.append('delimiter', ';'); return apiRequest<EtlRun>(`/api/v1/companies/${activeCompany.id}/etl-runs/import`, { method: 'POST', body: form }) }, onSuccess: () => client.invalidateQueries({ queryKey: key }) })
  const execute = useMutation({ mutationFn: (id: string) => apiRequest<EtlRun>(`/api/v1/companies/${activeCompany.id}/etl-runs/${id}/execute`, { method: 'POST' }), onSuccess: () => client.invalidateQueries({ queryKey: key }) })
  return <Stack spacing={2}><Typography variant="h4">Legacy ETL</Typography>{(upload.isError || execute.isError) && <Alert severity="error">Import nije završen. Proverite redosled tabela i sadržaj fajla.</Alert>}<Paper sx={{ p: 2 }}><Stack direction={{ xs: 'column', md: 'row' }} spacing={2}><TextField select label="Tabela" value={sourceTable} onChange={e => setSourceTable(e.target.value)}>{tables.map(x => <MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><Button component="label" variant="outlined">{file?.name ?? 'Izaberi CSV'}<input hidden type="file" accept=".csv,.txt" onChange={e => setFile(e.target.files?.[0])}/></Button><Button variant="contained" disabled={!file || upload.isPending} onClick={() => upload.mutate()}>Validiraj i pripremi</Button></Stack></Paper><Paper sx={{ overflowX: 'auto' }}><Table size="small"><TableHead><TableRow><TableCell>Fajl</TableCell><TableCell>Tabela</TableCell><TableCell>Faza</TableCell><TableCell>Redovi</TableCell><TableCell>Quarantine</TableCell><TableCell>Akcija</TableCell></TableRow></TableHead><TableBody>{runs.data?.map(run => <TableRow key={run.id}><TableCell>{run.sourceFile}</TableCell><TableCell>{run.sourceTable}</TableCell><TableCell>{run.stage}</TableCell><TableCell>{run.importedRows}/{run.sourceRows}</TableCell><TableCell>{run.quarantinedRows}</TableCell><TableCell>{run.stage === 'Staged' && <Button onClick={() => execute.mutate(run.id)}>Izvrši</Button>}</TableCell></TableRow>)}</TableBody></Table></Paper></Stack>
}
